FROM node:alpine

WORKDIR /usr/app

COPY ./tsconfig.json .

COPY ./package*.json .

RUN npm config set prefer-offline true  

RUN npm ci

ENTRYPOINT npx wait-port rabbit:5672 && \
           npm run start:dev